### ISSUE TITLE
Insufficient memory

### ISSUE THREAD

**Issue by hanxuel** [drethage/fully-convolutional-point-network#5]
Hi, whenever I do data.prepare to extract samples from scene, it gives error that memory is insufficient. When I reduce the number of scenes in the train_split set, it starts to work.
I'd like to know how much RAM do you use for training?
I use 1 core with memory 14000M, but it seems far less sufficient.

**Comment by drethage** [comment]
Hi hanxuel, I worked on a machine with 8 cores and 32GB of RAM. It may be necessary to have a bit more RAM. More cores will certainly speed up dataset preparation too.
